export const MOVIES_UPDATE_LIST = 'MOVIES_UPDATE_LIST'
export const MOVIES_SET_FETCHING = 'MOVIES_SET_FETCHING'
export const MOVIES_SET_ITEM = 'MOVIES_SET_ITEM'
export const MOVIES_SET_PAGE = 'MOVIES_SET_PAGE'